version: '3'
services:
  todo-frontend:
    stdin_open: true
    tty: true
    build: ./todo-frontend
    ports:
      - '3001:3001'
    networks: 
      - mern-app
    depends_on:
      - todo-backend
  todo-backend:
    build: ./todo-backend
    ports:
      - '3000:3000'
    networks: 
      - mern-app  
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - mern-app  
networks: 
    mern-app:
      driver: 'bridge'    